# tmp

# Main config file
title: ð•¿ð–ð–Š ð•¾ð–žð–“ð–†ð–Œð–”ð–Œð–šð–Š ð–”ð–‹ ð•¾ð–†ð–™ð–†ð–“
email: syn.of.satan@gmail.com
description: >- # `>-` means to ignore newlines until "baseurl:"
  The (Official) Synagogue of Satan is not with assosiated anybody.
  We are a Non-Profit organization openly dedicated to the
  acceptance of Man's true natureâ€”that of a carnal beast, living in a
  cosmos that is indifferent to our existence.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://the-synagogue-of-satan.github.io"
twitter_username: synofsatan
github_username:  the-synagogue-of-satan

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

